### ISSUE TITLE
API Contacts Post not working

### ISSUE THREAD

**Issue by luiskugel** [flipswitchingmonkey/n8n-nodes-lexoffice-api#1]
The POST Request for Contacts throws this Error, when used:

`ERROR: Your request is invalid or could not be processed by the service
406 - {"requestId":"25d9738a-6e60-4778-9c2e-2989290f5bb7","IssueList":[{"i18nKey":"missing_entity","source":"roles.customer or roles.vendor","type":"validation_failure"},{"i18nKey":"missing_entity","source":"company or person","type":"validation_failure"}]}`

**Comment by flipswitchingmonkey** [comment]
Yeah that was a stupid mistake with how the Body parameter was assigned (namely, it wasn't ;) 
Fixed now in 0.1.2 and I just published the npm pkg
